export const CONFIG = {
    USE_MOCK_API: true,
    MOCK_FETCH_DELAY: 1500,
    AUTH_CHECK_ENABLED: false,
    VISUAL_IMPAIRED_VALUE: 1.25,
    AUDIO_DIALOG_VOLUME: 0.5,
    AUDIO_BACKGROUND_VOLUME: 0.3
}