export const CONFIG = {
    USE_MOCK_API: true,
    MOCK_FETCH_DELAY: 500,
    AUTH_CHECK_ENABLED: false,
    VISUAL_IMPAIRED_VALUE: 1.2,
    AUDIO_DIALOG_VOLUME: 0.7,
    AUDIO_BACKGROUND_VOLUME: 0.15,
    SCENE_DIALOG_CHANGE_DELAY: 3000
}